// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // url: process.env['DATABASE_URL'],
    // 💡 核心：换成你刚才用 Docker 启动的 Postgres 连接串
    // 格式：postgresql://用户名:密码@主机名:端口号/数据库名
    url: 'postgresql://postgres:mysecretpassword@127.0.0.1:5432/nest_study',
  },
});
